### ISSUE TITLE
Not compatible with latest ESX code

### ISSUE THREAD

**Issue by iliasroleplay** [suppatimmo/esx_GangScript#2]
Not an issue, just a warning for people who have the latest ESX

**Comment by suppatimmo** [comment]
I was writing this script like a month ago for latest ESX and it was working pretty well.
I am not going to update this code anymore, but you can pull requests :)

**Comment by suppatimmo** [comment]
@iliasroleplay , have you tried to change "pz:" to "esx:" in event handlers? :)

**Comment by iliasroleplay** [comment]
sorry didnt see your comment, was busy, i will try your new commit and tell you if it works with 383acef which is the newest for ESX

**Comment by suppatimmo** [comment]
Alright. I was used to change "esx:" and "esx_" to "pz:"/"pz_", because I was using TigoAntiCheat, where all esx: triggers are banned automatically :P

**Comment by iliasroleplay** [comment]
works great, however is it possible to authorize, vehicles no such config in the config.lua

**Comment by suppatimmo** [comment]
Now it's working very well, you can add cars to SQL with jobname same as gang name, then check your gang garage :). I was wondering about adding space to put cars into gang, but didn't have much time. You can open new ticket, I'll think about it

**Comment by iliasroleplay** [comment]
superb!
