### ISSUE TITLE
Blips glich on map after adding several gangs

### ISSUE THREAD

**Issue by CarlBishop** [suppatimmo/esx_GangScript#3]
Hello and thanks for this very useful script.

I like it very much and helps me a lot on creating factions on server.

I found a strange issue.

After added 17 gangs, I found difficult or impossible to click on a blip in the map and setting a waypoint.

No issue with 2 or 3 gangs.

I ckecked one by one the resources on the server and the issue is not related to others script.

Did you ever experienved this kind of issue?

Thank you for any hint you can give to me.

**Comment by CarlBishop** [comment]
Seems the max number of gangs before the issue happens is 5

**Comment by suppatimmo** [comment]
Hello! Thanks for kind words. 
Could you please paste your config file? :) I'll check it.

**Comment by CarlBishop** [comment]
sure

Code on pastebin, link on next reply

I just added the wash option in order to remove or allow the washmoney feature

This i the mail.lua client section where I added the wash option

						elseif CurrentAction == 'menu_boss_actions' then		
							ESX.UI.Menu.CloseAll()
							TriggerEvent('esx_society:openBossMenu', v.JobName, function(data, menu)
							menu.close()
							CurrentAction     = 'menu_boss_actions'
							CurrentActionMsg  = _U('open_bossmenu')
							CurrentActionData = {}
							end, {wash = v.Wash}, {grades = false})

**Comment by suppatimmo** [comment]
Oh, may I ask you to paste it on pastebin or anywhere else? I need proper indentation :p 
pastebin.com
wklejto.pl

**Comment by CarlBishop** [comment]
yes sure

**Comment by CarlBishop** [comment]
sorry for bumping the issue.
Did you get a chance to check it?

**Comment by suppatimmo** [comment]
It's ok. I am really tired of private projects, that's why I haven't checked it yet. Maybe I'll do it today, but I cannot guarantee.

**Comment by suppatimmo** [comment]
@peppinoita, 
I don't have a GTA server with ESX, and the current, latest version of this framework just doesn't work properly on Linux. It follows that I have no way of even trying to fix the problem. I'll leave this ticket open, so maybe someone, who has access to stable server would like to fix it. Best regards

**Comment by CarlBishop** [comment]
Thank you I fixed

**Comment by suppatimmo** [comment]
@peppinoita if you have fixed this issue, could you please pull request with the solution? Other users will appreciate this :) thanks in advance!

**Comment by CarlBishop** [comment]
yes tomorrow I will write what I have done, but the issue was caused by myself when I modified the script

**Comment by CarlBishop** [comment]
So the issue was caused by me, I added a valua in the config file to define with gangs could wash the money and this caused the glich
![image](https://user-images.githubusercontent.com/12203647/108190311-10321600-7112-11eb-8def-d38083446b8c.png)
Once removed everything went good.
