### ISSUE TITLE
Add Billing

### ISSUE THREAD

**Issue by ghost** [suppatimmo/esx_GangScript#4]
Hello Boss, i try to find your discord for contact but im find nothing.
Im trying to add billing for adapt this script on other job (like used vehicle, ammunation, vanilla and other...)
can you help me? or simply make option to enable billing on desired job if active?

example in config.lua: 
Config.Gangs = {
	Ballas = {..
EnableBilling = True
..
after enable billing, with F6, or other key, i can open billing menù

(sorry for my bad english)

thanks in advance

**Comment by suppatimmo** [comment]
Is the billing implemented in another script? You need to tell me more about this.

**Comment by ghost** [comment]
this is a classic function

```
function OpenBillingMenu()

  ESX.UI.Menu.Open(
    'dialog', GetCurrentResourceName(), 'billing',
    {
      title = _U('billing_amount')
    },
    function(data, menu)
    
      local amount = tonumber(data.value)
      local player, distance = ESX.Game.GetClosestPlayer()

      if player ~= -1 and distance <= 3.0 then

        menu.close()
        if amount == nil then
            ESX.ShowNotification(_U('amount_invalid'))
        else
            TriggerServerEvent('esx_billing:sendBill', GetPlayerServerId(player), 'society_bahamas', _U('billing'), amount)
        end

      else
        ESX.ShowNotification(_U('no_players_nearby'))
		
      end

    end,
    function(data, menu)
        menu.close()
    end
  )
end
```

can find easy complete function in client script of this resource https://github.com/esx-community/esx_unicornjob

**Comment by suppatimmo** [comment]
So to be clear with everything. You want me to do an option in cfg, that will enable the billing menu option in F6 using this function?

**Comment by ghost** [comment]
I would like to give the possibility to a specific job, to make invoices if in the config it is true

**Comment by suppatimmo** [comment]
Actually, I don't even have any FiveM server to make tests. I'll try to do it for you without testing, but you need to give me some time, cuz I am busy in life.

**Comment by ghost** [comment]
ok boss.. we can test togheter

**Comment by suppatimmo** [comment]
@marlborosmoke Actually a friend of mine gave me an empty server for testing purposes. I'll have time tomorrow, in the evening, so please be patient :)
