### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by ryan11444** [suppatimmo/esx_GangScript#6]
I'm trying to add the sql file to my database, it adds everything except the job_grades. It's giving me errors saying unexpected beginning of statement. Here is the sql code. Can you help me please? I don't understand what's wrong.

SQL:

INSERT INTO `addon_account` (name, label, shared) VALUES 
	('society_soamc', 'SOA MC', 1)
;

INSERT INTO `datastore` (name, label, shared) VALUES 
	('society_soamc', 'SOA MC', 1)
;

INSERT INTO `addon_inventory` (name, label, shared) VALUES 
	('society_soamc', 'SOA MC', 1)
;

INSERT INTO `jobs` (`name`, `label`, `whitelisted`) VALUES
('soamc', 'SOA MC', 1);
;

INSERT INTO `job_grades` (`job_name`, `grade`, `name`, `label`, `salary`, `skin_male`, `skin_female`) VALUES
('soamc', 0, 'prospect', 'Prospect', 400, '{}', '{}'),
('soamc', 1, 'member', 'Member', 800, '{}', '{}'),
('soamc', 2, 'roadcaptain', 'Road Captain', 1000, '{}', '{}'),
('soamc', 3, 'sgtatarms', 'Sgt At Arms', 1200, '{}', '{}'),
('soamc', 4, 'treasurer', 'Treasurer', 1400, '{}', '{}')
('soamc', 5, 'secretary', 'Secretary', 1500, '{}', '{}'),
('soamc', 6, 'vpresident', 'V President', 1800, '{}', '{}'),
('soamc', 7, 'president', 'President', 2000, '{}', '{}');

**Comment by Jeydolen** [comment]
You did not put a comma on the 5th line and that's the only error I can see in your SQL.

**Comment by ryan11444** [comment]
Can't believe I missed that. That was the problem...but now, I'm having a problem where when I use the armory, it puts 2 "undefined" items in my inventory. Any ideas on how to fix this?

**Comment by Jeydolen** [comment]
Yeah, I have the same issue and I was thinking this was because I'm using
weapons as items. Do you ? I'll try to fix this problem and tell you if I
did.

**Comment by Jeydolen** [comment]
Okay, i've found the problem :
	
    ESX.UI.Menu.Open(
      'default', GetCurrentResourceName(), 'armory',
      {
        title    = _U('armory'),
        align    = 'left',
        elements = elements,
      },
      function(data, menu)
		if data.current.value == 'get_weapon' then
			OpenGetWeaponMenu(societyName)
		elseif data.current.value == 'put_weapon' then
			OpenPutWeaponMenu(societyName)
        elseif data.current.value == 'put_stock' then
			OpenPutStocksMenu(societyName)
		elseif data.current.value == 'get_stock' then
			OpenGetStocksMenu(societyName)
		end
		
		local weapon = data.current.value
		--TriggerServerEvent('esx_gangScript:giveWeapon', weapon,  1)
      end,
      function(data, menu)
        menu.close()
        CurrentAction     = 'menu_armory'
        CurrentActionMsg  = _U('open_armory')
        CurrentActionData = {station = station}
      end
   )
end


You have to comment TriggerServerEvent('esx_gangScript:giveWeapon', weapon,  1) and the problem will be stopped !

**Comment by ryan11444** [comment]
Yeah, that fixed it. Is there a way to stop it from giving 200 ammo when you pull the gun out tho? I put a pistol with 42 ammo in, when I pull it out, it has over 200.

**Comment by Jeydolen** [comment]
ESX.RegisterServerCallback('esx_gangScript:removeArmoryWeapon',
function(source, cb, weaponName, societyName)
local xPlayer = ESX.GetPlayerFromId(source)
xPlayer.addWeapon(weaponName, 500)
As you can see line 125 in server/main.lua
You have a xPlayer.addWeapon(weaponName, 500)

500 is the number of ammo given when you retrieve the weapon from the
armory, you can change this value or do a little system to get your
previous value and give it for this weapon but it's more complicated.
